
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: fcy20020624


mybatis:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.example.demo.pojo # 具体到User类所在的目录
#    configuration:
#        map-underscore-to-camel-case: true
server:
    port: 8080
